# Generated by Django 6.0.1 on 2026-02-02 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.TextField(
                blank=True, help_text="Short bio or description", max_length=500
            ),
        ),
    ]
