# Generated by Django 6.0.1 on 2026-02-03 08:14

"""
Migration to clear legacy plain-text security tokens.

Security Change:
    Previously, email verification tokens and password reset tokens were stored
    as plain text. Now they are hashed with SHA256 before storage.

    This migration clears all existing tokens because:
    1. Old plain-text tokens won't match hashed lookups
    2. Users can request new tokens if needed
    3. It's safer than attempting to hash existing tokens (which could fail)

Impact:
    - Users with pending email verification must request a new verification email
    - Users with pending password reset must request a new reset email
"""

from django.db import migrations


def clear_legacy_tokens(apps, schema_editor):
    """
    Clear all existing security tokens.

    This is necessary because the token storage format changed from
    plain text to SHA256 hashed values. Existing tokens would not
    match the new hashed lookups.
    """
    User = apps.get_model("users", "User")

    # Clear email verification tokens
    User.objects.filter(email_verification_token__gt="").update(
        email_verification_token="",
        email_verification_sent_at=None,
    )

    # Clear password reset tokens
    User.objects.filter(password_reset_token__gt="").update(
        password_reset_token="",
        password_reset_sent_at=None,
    )


def reverse_noop(apps, schema_editor):
    """
    No-op reverse - can't restore tokens after clearing.
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_add_bio_field"),
    ]

    operations = [
        migrations.RunPython(
            clear_legacy_tokens,
            reverse_noop,
            elidable=True,  # Can skip if squashing migrations
        ),
    ]
