# Generated by Django 6.0.1 on 2026-02-03 17:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_clear_legacy_tokens"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthAuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("login_success", "Login Success"),
                            ("login_failure", "Login Failure"),
                            ("logout", "Logout"),
                            ("register", "Registration"),
                            ("token_refresh", "Token Refresh"),
                            ("token_refresh_failure", "Token Refresh Failure"),
                            ("password_reset_request", "Password Reset Request"),
                            ("password_reset_confirm", "Password Reset Confirm"),
                            ("password_change", "Password Change"),
                            ("email_verify", "Email Verification"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Email attempted (for failed logins with unknown users)",
                        max_length=254,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional event-specific data",
                    ),
                ),
                ("success", models.BooleanField(default=True)),
                ("failure_reason", models.CharField(blank=True, max_length=100)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Auth Audit Log",
                "verbose_name_plural": "Auth Audit Logs",
                "db_table": "auth_audit_logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["event_type", "timestamp"],
                        name="auth_audit__event_t_d474dc_idx",
                    ),
                    models.Index(
                        fields=["user", "timestamp"],
                        name="auth_audit__user_id_581b94_idx",
                    ),
                    models.Index(
                        fields=["ip_address", "timestamp"],
                        name="auth_audit__ip_addr_731146_idx",
                    ),
                ],
            },
        ),
    ]
