# Generated by Django 6.0.1 on 2026-02-01 21:20

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("locations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cafe",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=200)),
                ("slug", models.SlugField(max_length=220, unique=True)),
                (
                    "description",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Localized description: {"en": "...", "de": "..."}',
                    ),
                ),
                (
                    "overview",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Localized overview/tagline: {"en": "...", "de": "..."}',
                    ),
                ),
                ("address", models.CharField(max_length=300)),
                ("address_line_2", models.CharField(blank=True, max_length=200)),
                ("postal_code", models.CharField(blank=True, max_length=20)),
                ("city", models.CharField(db_index=True, max_length=100)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("website", models.URLField(blank=True, max_length=500)),
                (
                    "social_links",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='{"instagram": "url", "facebook": "url", "twitter": "url"}',
                    ),
                ),
                ("image_url", models.URLField(blank=True, max_length=500)),
                ("thumbnail_url", models.URLField(blank=True, max_length=500)),
                (
                    "gallery",
                    models.JSONField(
                        blank=True, default=list, help_text='["url1", "url2", ...]'
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("cafe", "Café"),
                            ("coworking", "Coworking Space"),
                            ("library", "Library"),
                            ("hotel_lobby", "Hotel Lobby"),
                            ("restaurant", "Restaurant"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        default="cafe",
                        max_length=20,
                    ),
                ),
                (
                    "category_color",
                    models.CharField(
                        default="#6B7280",
                        help_text="Hex color for category badge",
                        max_length=7,
                    ),
                ),
                (
                    "price_level",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "$"), (2, "$$"), (3, "$$$"), (4, "$$$$")],
                        db_index=True,
                        default=2,
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='["wifi", "quiet", "outdoor", "power_outlets"]',
                    ),
                ),
                (
                    "amenities",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='{"wifi": true, "wifi_speed": "50mbps", "power_outlets": true, ...}',
                    ),
                ),
                (
                    "opening_hours",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='{"monday": {"open": "08:00", "close": "18:00"}, ...}',
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        blank=True,
                        help_text="IANA timezone, inherits from location if empty",
                        max_length=50,
                    ),
                ),
                (
                    "rating_avg",
                    models.DecimalField(
                        db_index=True,
                        decimal_places=2,
                        default=0,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("rating_count", models.PositiveIntegerField(default=0)),
                (
                    "rating_wifi",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "rating_power",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "rating_noise",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "rating_coffee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("is_featured", models.BooleanField(db_index=True, default=False)),
                ("is_verified", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "allows_contact",
                    models.BooleanField(
                        default=True, help_text="Show contact form on detail page"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cafes",
                        to="locations.location",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_cafes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "cafes",
                "ordering": ["-rating_avg", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Bookmark",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookmarks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cafe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookmarks",
                        to="cafes.cafe",
                    ),
                ),
            ],
            options={
                "db_table": "bookmarks",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="cafe",
            index=models.Index(
                fields=["location", "is_active"], name="cafes_locatio_ed33f5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cafe",
            index=models.Index(
                fields=["category", "is_active"], name="cafes_categor_2e4a32_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cafe",
            index=models.Index(
                fields=["city", "is_active"], name="cafes_city_cff34e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cafe",
            index=models.Index(
                fields=["is_featured", "rating_avg"], name="cafes_is_feat_2a543e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cafe",
            index=models.Index(
                fields=["price_level", "rating_avg"], name="cafes_price_l_742dc0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cafe",
            index=models.Index(
                fields=["-rating_avg", "-rating_count"], name="cafes_rating__56e057_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="bookmark",
            unique_together={("user", "cafe")},
        ),
    ]
