# Generated by Django 6.0.1 on 2026-02-02 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cafes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cafe",
            name="logo_url",
            field=models.URLField(
                blank=True, help_text="Brand logo/badge image URL", max_length=500
            ),
        ),
        migrations.AddField(
            model_name="cafe",
            name="owner_role",
            field=models.CharField(
                blank=True,
                help_text="Owner's role, e.g. 'Owner & café designer', 'F&B Manager'",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="cafe",
            name="category",
            field=models.CharField(
                choices=[
                    ("cafe", "Café"),
                    ("coworking", "Coworking Space"),
                    ("restaurant", "Restaurant"),
                    ("hotel_cafe", "Hotel Café"),
                    ("library", "Library"),
                    ("other", "Other"),
                ],
                db_index=True,
                default="cafe",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="cafe",
            name="tags",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Features array using Feature enum values: ["fast_wifi", "quiet", "outdoor_seating"]',
            ),
        ),
    ]
