# Generated by Django 6.0.1 on 2026-02-01 21:20

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cafes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rating_overall",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "rating_wifi",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "rating_power",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "rating_noise",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Higher = quieter",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "rating_coffee",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("text", models.TextField(max_length=2000)),
                (
                    "language",
                    models.CharField(
                        default="en",
                        help_text="Language code (e.g., en, de)",
                        max_length=5,
                    ),
                ),
                (
                    "photos",
                    models.JSONField(
                        blank=True, default=list, help_text='["url1", "url2", ...]'
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False, help_text="Review from verified visit"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cafe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="cafes.cafe",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "reviews",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["cafe", "is_active", "-created_at"],
                        name="reviews_cafe_id_b6bb4b_idx",
                    ),
                    models.Index(
                        fields=["user", "-created_at"],
                        name="reviews_user_id_9f7b05_idx",
                    ),
                ],
                "unique_together": {("cafe", "user")},
            },
        ),
    ]
