# Generated by Django 6.0.1 on 2026-02-01 21:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.JSONField(
                        default=dict,
                        help_text='Localized name: {"en": "Berlin", "de": "Berlin"}',
                    ),
                ),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("country", models.CharField(db_index=True, max_length=100)),
                ("country_code", models.CharField(blank=True, max_length=2)),
                ("region", models.CharField(blank=True, max_length=100)),
                (
                    "timezone",
                    models.CharField(
                        default="UTC",
                        help_text="IANA timezone (e.g., Europe/Berlin)",
                        max_length=50,
                    ),
                ),
                ("image_url", models.URLField(blank=True, max_length=500)),
                ("thumbnail_url", models.URLField(blank=True, max_length=500)),
                ("hero_image_url", models.URLField(blank=True, max_length=500)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("cafe_count", models.PositiveIntegerField(default=0)),
                ("is_featured", models.BooleanField(db_index=True, default=False)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "locations",
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["country", "is_active"],
                        name="locations_country_f798f6_idx",
                    ),
                    models.Index(
                        fields=["is_featured", "cafe_count"],
                        name="locations_is_feat_5fa237_idx",
                    ),
                ],
            },
        ),
    ]
